language: rust

rust:
  - nightly
  - stable

cache: cargo

addons:
  apt:
    packages:
    - libxxf86vm-dev

script:
  - cargo build --verbose
  - [ $TRAVIS_OS_NAME = osx ] && cargo build --target x86_64-apple-ios
  - cargo test --verbose

os:
  - linux
  - osx

after_success:
  - |
      [ $TRAVIS_BRANCH = master ] &&
      [ $TRAVIS_PULL_REQUEST = false ] &&
      cargo publish --token ${CRATESIO_TOKEN}
