[package]

name = "glutin"
version = "0.0.3-pre"
authors = ["tomaka <pierre.krieger1708@gmail.com>"]
description = "Cross-plaform OpenGL context provider."
keywords = ["windowing", "opengl"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/tomaka/glutin"
documentation = "http://tomaka.github.io/glutin/"
build = "build.rs"

[features]
default = ["window"]
window = []
headless = []

[dependencies.gl_common]
gl_common = "*"

[build-dependencies]
gl_generator = "*"

[target.i686-pc-windows-gnu.dependencies.winapi]
version = "^0.0.3"
features = ["gdi32", "kernel32", "user32"]

[target.x86_64-pc-windows-gnu.dependencies.winapi]
version = "^0.0.3"
features = ["gdi32", "kernel32", "user32"]
