[package]

name = "glutin"
version = "0.0.1"
authors = ["tomaka <pierre.krieger1708@gmail.com>"]

[features]
default = ["window"]
window = []
headless = []

[dependencies.compile_msg]
git = "https://github.com/huonw/compile_msg"

[dependencies.gl_generator]
git = "https://github.com/bjz/gl-rs"

[target.arm-linux-androideabi.dependencies.android_glue]
git = "https://github.com/tomaka/android-rs-glue"

[target.i686-apple-darwin.dependencies.cocoa]
git = "https://github.com/DavidPartouche/rust-cocoa"

[target.x86_64-apple-darwin.dependencies.cocoa]
git = "https://github.com/DavidPartouche/rust-cocoa"

[target.i686-apple-darwin.dependencies.core_foundation]
git = "https://github.com/servo/rust-core-foundation"

[target.x86_64-apple-darwin.dependencies.core_foundation]
git = "https://github.com/servo/rust-core-foundation"
