[package]
name = "winit"
version = "0.5.1"
authors = ["The winit contributors, Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Cross-platform window creation library."
keywords = ["windowing"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/tomaka/winit"
documentation = "https://tomaka.github.io/winit/"

[dependencies]
lazy_static = "0.1.10"
libc = "0.2"
shared_library = "0.1.0"

[target.arm-linux-androideabi.dependencies.android_glue]
version = "0.2"

[target.'cfg(target_os="ios")'.dependencies]
objc = "0.2"

[target.'cfg(target_os="macos")'.dependencies]
objc = "0.2"
cgl = "0.1"
cocoa = "0.3"
core-foundation = "0"
core-graphics = "0.3"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
shell32-sys = "0.1"
gdi32-sys = "0.1"
user32-sys = "~0.1.2"
kernel32-sys = "0.2"
dwmapi-sys = "0.1"

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd"))'.dependencies]
wayland-client = { version = "0.5.4", features = ["dlopen"] }
wayland-kbd = "0.3.3"
wayland-window = "0.2.2"
x11-dl = "~2.4"
