version: 2

jobs:

  test:
    working_directory: ~/tgst
    docker:
      - image: tomaka/cargo-apk
    steps:
      - checkout
      - restore_cache:
          key: test-cache-{{ checksum "Cargo.lock" }}
      - run: cargo apk build --example window
      - save_cache:
          key: test-cache-{{ checksum "Cargo.lock" }}
          paths:
            - target

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
